### ISSUE TITLE
sub-peepers and their methods: abstract classes?

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/peepingtom#24]
I think that with out current idea of sub-Peepers, there would be quite a bit of code duplication, or weird inheritance networks.

What do you think of having a few abstract classes with topic-specific methods, and then our peepers could inherit from any combination of those, while adding whatever connection is needed?

**Comment by alisterburt** [comment]
Yeah this sounds good, did you have any specific examples in mind?

**Comment by brisvag** [comment]
For example, particle-related operations would be in one of these abstract classes. Then, a Peeper used for just particles can use them, as well as a `RefinementPeeper` that would also inherit from an image-related abstract class. this woudl allow the 2 peeper to reuse code, while having (for example) different constructor for easier creation.

**Comment by brisvag** [comment]
I'm not so sure anymore about this. The more I play around with the idea, and the more I get convinced that everything should be available in Peeper, so that if any data is added, no matter how you started you will be able to handle it.

We should probably set up a bit better the `io_` module and have an all-encompassing read function (probably with modes) so that creating a peeper is seamless. this can probably be accessed by the peeper with an `add_data()` method, so that i can be used on init as well as later on.

As for everything else (displaying, analysis...), we should probably put everything in a generic peeper.

**Comment by alisterburt** [comment]
Gotcha, I think this can work and indeed may simplify things for eventual
users!

How about setting it up so that in its constructor the `Peeper` takes only
a list of `DataCrate`s

We could then implement any custom construction by factory methods such as
`from_relion_refinement_directory`, `from_relion_refinement_star_file` etc.

This gets verbose quickly, subpeepers could then just be `Peeper`s which
have a few modes for reading the necessary files etc, e.g. RefinementPeeper
knows during construction the things it could be looking for and constructs
from the correct `from_*` method?

**Comment by brisvag** [comment]
I agree until the last point: I think it's strange and unintuitive that the object you're holding only differs in construction methods.
I would go with something like numpy's `np.array()`, which "alsways" spitsout a ndarray and it's only job is to guess from the input how to construct it.

**Comment by alisterburt** [comment]
hmm okay, I'm having a hard time seeing how we get everything to match up
when we try to infer everything from the data itself but it's a nice goal!

**Comment by brisvag** [comment]
Obsolete/closed by #68 .
