### ISSUE TITLE
problems in refactored io

### ISSUE THREAD

**Issue by alisterburt** [gutsche-lab/peepingtom#59]
There are a couple of issues with the way the IO has been refactored, listing them here so I can try to fix them

- there seems to be a misunderstanding about what a STAR file is/means, it doesn't necessarily contain particles and a dynamo table file is not a star file

- consequently, euler2matrix should not be a function only related to STAR file handling, but generally for handling euler angles in any file type that may come with euler angles (relion star files, dynamo tables, PEET/EMAN/STOPGAP etc etc)

- star conventions now contains dynamo table info, wrong for above reasons

- read_star is a monster of a function, difficult to customise file reading with the current conventions because we don't always know what a star file will contain in advance in terms of properties we might want to use

- read_star is difficult to refactor into smaller pieces because in the various nested loops it calls data from various other stages, this should be handled in some kind of `StarHandler` object

**Comment by alisterburt** [comment]
it's also really not clear what the `name_regex` parameter actually does, how does it affect the way data is returned?

**Comment by alisterburt** [comment]
playing with this now, shifts are also not correctly parsed for rln3.1 star files. They default to 0 because we aren't looking for the right header

**Comment by brisvag** [comment]
I'll answer in order:
- that's definitely an assumption I had. What else might comes from starfiles that we care about in peepingtom? What do you mean with dynamo table file not being a starfile? I thought that we were only reading actual star files generated by dynamo, so far...
- agree on this, if we plan to read those things this should not be duplicated! I moved it here mostly because as you know I dound the eulerhelper module more confusing than helpful :P
- see above
- yup, that mess needs untangling. I'll take a look #60 now!
- I'm not sure this is doable. Those points where it uses data from different places are important! You could save them in some additional data structure and move around that one instead of a variable, but I'm not sure how much better it is. I'll see what you did so far!

**Comment by brisvag** [comment]
I see now what you mean by dynamo table files. I don't know when the confusion started, but I thought they were actual starfiles generated by dynamo that we were reading! Never noticed in previous versions that `dynamotable` was being called, somehowe :P

**Comment by brisvag** [comment]
Mostly closed by #60 and #62.
