### ISSUE TITLE
Transformblock

### ISSUE THREAD

**Issue by brisvag** [gutsche-lab/peepingtom#72]
Transformblock is currently broken by #69 , because it relied heavily on reshaping, which is both impossible on xarray, and against its strengths. We should rewrite it. While we are at it, I'll bring up a conversation we probably had already but haven't concluded as far as I remember:

I think Transformblock should be a simple ParticleBlock subclass that allows for a different depiction, but the transformation function should live in an `Alchemist` that goes from Particle + Transform to Particle, for example.

**Comment by alisterburt** [comment]
Cool thanks for raising the issue, I might need some help fixing it because I'm not familiar with xarray and the way I implemented this does indeed rely on quite a lot of broadcasting wizardry. I guess I just have to specifically add those new dimensions to each array and give them names?

From memory we (or at least I) ended up thinking it was better to have the two things inherit from a common base class (which is currently `OrientedPointBlock` but could become `ParticleModel` or something) - is that incompatible with something I'm not seeing now?

**Comment by brisvag** [comment]
I would have to play around with it, but the basic idea is that broadcasting happens on dimension name basis (if available), rather than order. Try this stuff to get an idea:
```python
a = xr.DataArray([[1, 2], [3, 4]], dims=['x', 'y'])
b = xr.DataArray([10, 20], dims=['y'])
c = xr.DataArray([10, 20], dims=['x'])
d = xr.DataArray([10, 20], dims=['a'])
a+b
a+c
a+d
a + np.random.rand(2)
```

**Comment by brisvag** [comment]
As for subclassing: Yeah that's fine, but I'm talking about where the code for performing the transformation should live. And I think that fits on an alchemist, rather than being simply a visualization "trick".
It's similar to the discussion we had about line block, and the fact that I think the line block should just be defined by a list of points, and have helper methods to "treat" it like a line (e.g: distance from)... But the "generation" of the line as a set of points should either live on an alchemist that generates a pointblock (probably not), on a the line depictor (since that set of points only serves for depiction) or even better on the napari side (now on the radar :P).

**Comment by alisterburt** [comment]
Thanks for the example! Okay I think I'm with you, you want to move the apply_on method to be an alchemist and leave the class as-is (or nearly), sounds reasonable!

**Comment by brisvag** [comment]
Outdated.
